### ISSUE TITLE
複合代入演算子 「+=」の説明を追加したい

### ISSUE THREAD

**Issue by Slephy** [hcpc-hokudai/HCPC_welcom_2024#3]
5.md, 6.mdにて += が使われていますが、もう少し詳しく触れた方がよいかもしれません。
i = i + 1 のような処理は、代入と等号を混乱しがちな初心者にとって難しいので説明を追加したいです。

修正の必要性、方向性について意見が欲しいです🙇‍♀️

（該当箇所へのリンク）
https://github.com/hcpc-hokudai/HCPC_welcome_2024/blob/22307e669a62ad82a2fb8dea1e1b6948d9e9e197/5.md?plain=1#L44-L47
https://github.com/hcpc-hokudai/HCPC_welcome_2024/blob/22307e669a62ad82a2fb8dea1e1b6948d9e9e197/6.md?plain=1#L52-L59

**Comment by Today017** [comment]
ありがとうございます！
説明を失念していました💦
取り急ぎ追加しておきます。
個人的には 2 章の変数のところで扱うのがよいと思っているのですが、これについて何か意見がありましたら言ってくださると幸いです🙇‍♀️

**Comment by Slephy** [comment]
2章では代入の説明をしていますから、この話題を扱うのに適切な場所だと思います。

**Comment by Today017** [comment]
ありがとうございます！複合代入演算子の説明を追加いたしました。
