### ISSUE TITLE
countの説明を修正

### ISSUE THREAD

**Issue by Slephy** [hcpc-hokudai/HCPC_welcom_2024#4]
「`x`の要素数」という表現に変えて、「`x`がいくつ含まれるか」「`x`が何個含まれるか」としてはどうでしょうか？

https://github.com/hcpc-hokudai/HCPC_welcome_2024/blob/993ed6dc1d0ed346df14dbc021a32d28f5bf2347/6.md?plain=1#L94
https://github.com/hcpc-hokudai/HCPC_welcome_2024/blob/993ed6dc1d0ed346df14dbc021a32d28f5bf2347/7.md?plain=1#L48

**Comment by titan-23** [comment]
良いと思います。
「xがいくつ含まれるか」に修正します。
